# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ym-nbdev-fresh',
                'doc_host': 'https://maiyishan.github.io',
                'git_url': 'https://github.com/maiyishan/ym-nbdev-fresh',
                'lib_path': 'ym_nbdev_fresh'},
  'syms': {'ym_nbdev_fresh.core': {'ym_nbdev_fresh.core.foo': ('core.html#foo', 'ym_nbdev_fresh/core.py')}}}